# -*- coding: utf-8 -*-
"""data_leakage_debug

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eLdIp1SFi9Pu-zRY7aWEFbM8fZvNOqbX
"""

import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

df = sns.load_dataset('titanic')
df['age'] = df['age'].fillna(df['age'].median())
df['sex'] = df['sex'].map({'male': 0, 'female': 1})

df['is_survived_copy'] = df['survived']

y = df['survived']
X_leaked = df.drop(columns=['survived']) # X كدة جواه العمود المسرب is_survived_copy!
X_leaked = X_leaked.select_dtypes(include=['number'])

X_train, X_test, y_train, y_test = train_test_split(X_leaked, y, test_size=0.2, random_state=42)

model_leaked = LogisticRegression()
model_leaked.fit(X_train, y_train)
y_pred_leaked = model_leaked.predict(X_test)

print("--- Data Leakage Simulation ---")
print("Accuracy with Leakage:", accuracy_score(y_test, y_pred_leaked)) # النتيجة: 1.0 (100%)

#التصحيح
X_fixed = df.drop(columns=['survived', 'is_survived_copy'])
X_fixed = X_fixed.select_dtypes(include=['number'])

X_train_f, X_test_f, y_train_f, y_test_f = train_test_split(X_fixed, y, test_size=0.2, random_state=42)

model_fixed = LogisticRegression()
model_fixed.fit(X_train_f, y_train_f)
y_pred_fixed = model_fixed.predict(X_test_f)

print("\n--- After Fixing Leakage ---")
print("Accuracy after Fix:", accuracy_score(y_test_f, y_pred_fixed)) # النتيجة الحقيقية: ~0.78-0.80