# -*- coding: utf-8 -*-
"""W3D2_Data_Cleaning.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AI6uwyqegRyjW5Icu-jAWvwoRjvLRUO4
"""

import pandas as pd
import seaborn as sns

df = sns.load_dataset('titanic')

print(df.isnull().sum())
print(df.info())
print(df.describe())

df['age'] = df['age'].fillna(df['age'].median())
df['embarked'] = df['embarked'].fillna(df['embarked'].mode()[0])
df = df.drop(columns=['deck'])

df['sex'] = df['sex'].map({'male': 0, 'female': 1})
df = pd.get_dummies(df, columns=['embarked'], drop_first=True)

label = df['survived']
features = df.drop(columns=['survived'])

df.to_csv("cleaned_data.csv", index=False)


# سبب اختيار طريقة التعامل مع القيم الناقصة لكل عمود:
# - age: استخدمت الـ median لأنه متأثرش بالقيم الشاذة (outliers).
# - embarked: استخدمت الـ mode لأنها داتا نصية ونسبة النقص فيها كانت قليلة جداً.
# - deck: مسحت العمود كله لأن نسبة النقص فيه كانت كبيرة جداً ومكانش هيضيف قيمة للنموذج.