# -*- coding: utf-8 -*-
"""W3D3_First_Model.py.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lcrTVDQ2TZ6thlNhQIHm73CseIEu_3OA
"""

import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

df = sns.load_dataset('titanic')
df['age'] = df['age'].fillna(df['age'].median())
df['sex'] = df['sex'].map({'male': 0, 'female': 1})


y=df['survived']
x=df.drop(columns=['survived'])
x=x.select_dtypes(include=['number'])
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)
model=LogisticRegression()
model.fit(x_train , y_train)
y_pred=model.predict(x_test)
acc=accuracy_score(y_test, y_pred)
print('accuracy :' ,acc)
# التعليق والتحليل:
# النتيجة ممتازة ومنطقية جداً (81%) كبداية لنموذج Logistic Regression بسيط.
# - لا يوجد Overfitting لأن الدقة ليست مرتفعة بشكل مبالغ فيه (مثل 99%).
# - لا يوجد Underfitting لأن النسبة جيدة وتتجاوز الـ 80%.
# - يمكن تحسين الدقة أكثر مستقبلاً بإضافة باقي الخصائص النصية بعد عمل One-Hot Encoding لها.