# -*- coding: utf-8 -*-
"""W3D4_Model_Comparison.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ggk8Tgfx4zY5MOR-HFwS4cdxNkSF-Fjw
"""

import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

df = sns.load_dataset('titanic')
df['age'] = df['age'].fillna(df['age'].median())
df['sex'] = df['sex'].map({'male': 0, 'female': 1})
y =df['survived']
x=df.drop(columns=['survived'])
x=x.select_dtypes(include=['number'])
x_train ,x_test ,y_train, y_test=train_test_split(x,y, test_size=0.20 , random_state=42)
LG_model=LogisticRegression()
LG_model.fit(x_train , y_train)
y_pred=LG_model.predict(x_test)
acc=accuracy_score( y_test, y_pred)
print("Logistic Regression Accuracy:", acc)

DT_model= DecisionTreeClassifier()
DT_model.fit(x_train,y_train)
y_pred=DT_model.predict(x_test)
acc=accuracy_score( y_test, y_pred)
print("Decision Tree Accuracy:", acc)

KNN_model= KNeighborsClassifier()
KNN_model.fit(x_train , y_train)
y_pred=KNN_model .predict(x_test)
acc=accuracy_score(y_test , y_pred)
print("KNN (Before Scaling) Accuracy:", acc)

scaler=StandardScaler()
x_train_scaled= scaler.fit_transform(x_train)
x_test_scaled= scaler.transform(x_test)

KNN_model.fit(x_train_scaled, y_train)
y_pred = KNN_model.predict(x_test_scaled)
acc_scaled = accuracy_score(y_test, y_pred)
print("KNN (After Scaling) Accuracy:", acc_scaled)
