# -*- coding: utf-8 -*-
"""w3d5_unsupervised_leakage

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_xZykYgMcQNnOKhoH3gajZthBJUhi-0F
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

df = sns.load_dataset('titanic')
df['age'] = df['age'].fillna(df['age'].median())
df['fare'] = df['fare'].fillna(df['fare'].median())

x=df[['age','fare']]
scaler=StandardScaler()
x_scaled=scaler.fit_transform(x)

kmeans = KMeans(n_clusters=3, random_state=42)
clusters = kmeans.fit_predict(x_scaled)

plt.scatter(x_scaled[:, 0], x_scaled[:, 1], c=clusters)
plt.show()